// src/components/portfolio/MainProjects.vue
<script setup lang="ts">
import { useLanguage } from "../../composables/useLanguage"
import AnimatedReveal from "./AnimatedReveal.vue"
import MainProject from "./MainProject.vue"
import type { Project, Software } from "../../types/portfolio"

defineProps<{
  projects:  Project[]
  softwares: Record<string, Software>
}>()

const { t } = useLanguage()
</script>

<template>
  <section id="projects" class="main-projects-section">
    <AnimatedReveal
      direction="bottom"
      :distance="50"
      :duration="0.8"
      :threshold="0.1"
      :initial-opacity="0"
      :final-opacity="1"
    >
      <h2 class="section-title">{{ t("projectsTitle") }}</h2>
    </AnimatedReveal>

    <div class="main-projects-section__list">
      <MainProject
        v-for="(project, idx) in projects"
        :key="idx"
        :project="project"
        :softwares="softwares"
        :index="idx"
      />
    </div>
  </section>
</template>

<style scoped>
.main-projects-section {
  padding-top: var(--spacing-2xl);
}

.main-projects-section__list {
  margin-top: var(--spacing-3xl);
}

@media (max-width: 768px) {
  .main-projects-section__list { margin-top: var(--spacing-xl); }
}
</style>

// src/components/projects/mainProjects.tsx
import React, { Component } from 'react';
import { LanguageContextType } from '../languageProvider';
import MainProject from './mainProject';
import { Project, Software } from '../../types';
import styles from './mainProjects.module.css';
import AnimatedComponent from '../AnimatedComponent';
//Context consumer for class components
import { LanguageContext } from '../languageProvider';

interface MainProjectsProps {
  projects: Project[];
  softwares: Record<string, Software>;
}

class MainProjects extends Component<MainProjectsProps> {
  static contextType = LanguageContext;
  context!: React.ContextType<typeof LanguageContext>;

  render() {
    const { projects, softwares } = this.props;
    const { t } = this.context as LanguageContextType;

    return (
      <section id="projects" className={`section ${styles.projectsSection}`}>
        <AnimatedComponent
          direction="bottom"
          distance={50}
          duration={0.8}
          once={true}
          threshold={0.1}
          initialOpacity={0}
          finalOpacity={1}
        >
          <h2 className={'sectionTitle'}>{t('projects.title')}</h2>
        </AnimatedComponent>

        <div className={styles.projectsList}>
          {projects.map((project, index) => (
            <MainProject
              key={index}
              project={project}
              softwares={softwares}
              index={index}
            />
          ))}
        </div>
      </section>
    );
  }
}

export default MainProjects;
