// src/animatedCounter.tsx
import { formatNumber, useIsInView } from "@/utils/Utils";
import { useRef, useEffect } from "react";

type AnimatedCounterProps = {
    from: number;
    to: number;
    duration?: number;
};

//Custom hook to handle isomorphic layout effect
const useIsomorphicLayoutEffect = typeof window !== 'undefined' ? useEffect : useEffect;

const AnimatedCounter = ({
    from,
    to,
    duration = 5,
}: AnimatedCounterProps) => {
    const ref = useRef<HTMLSpanElement>(null);
    const inView = useIsInView(ref, {
        once: true,
        rootMargin: '0px 0px 100px 0px' // Start animation when element is 100px below viewport
    });

    useIsomorphicLayoutEffect(() => {
        const element = ref.current;
        if (!element) return;
        if (!inView) return;

        //Set initial value
        element.textContent = String(from);

        //If reduced motion is enabled in system's preferences
        if (window.matchMedia("(prefers-reduced-motion)").matches) {
            element.textContent = formatNumber(to);
            return;
        }

        //Animation variables
        let startTime: number | null = null;
        let animationFrameId: number;

        //Animation function
        const animate = (timestamp: number) => {
            if (!startTime) startTime = timestamp;
            const progress = Math.min((timestamp - startTime) / (duration * 1000), 1);
            const currentValue = from + (to - from) * easeOut(progress);

            if (element) {
                element.textContent = formatNumber(currentValue);
            }

            if (progress < 1) {
                animationFrameId = requestAnimationFrame(animate);
            }
        };

        //Start animation
        animationFrameId = requestAnimationFrame(animate);

        //Cleanup
        return () => {
            cancelAnimationFrame(animationFrameId);
        };
    }, [from, to, duration, inView]);

    return <span ref={ref} />;
};

//Ease out function - similar to Framer Motion's "easeOut"
const easeOut = (x: number): number => {
    return 1 - Math.pow(1 - x, 2);
};

export default AnimatedCounter;

// src/components/portfolio/AnimatedCounter.vue
<script setup lang="ts">
import { ref, watch } from "vue"
import { useInView } from "../../composables/useInView"
import { formatNumber } from "../../lib/portfolio-utils"

interface Props {
  from:     number
  to:       number
  duration?: number
}

const props = withDefaults(defineProps<Props>(), {
  duration: 2,
})

const root = ref<HTMLSpanElement | null>(null)
const display = ref(formatNumber(props.from))
const { inView } = useInView(root, { once: true, rootMargin: "0px 0px 100px 0px" })

const easeOut = (x: number) => 1 - Math.pow(1 - x, 2)

watch(inView, (isInView) => {
  if (!isInView) return

  //honor the user's reduced-motion preference
  if (window.matchMedia("(prefers-reduced-motion)").matches) {
    display.value = formatNumber(props.to)
    return
  }

  const startTs = performance.now()
  const total = props.duration * 1000

  function tick(ts: number) {
    const progress = Math.min((ts - startTs) / total, 1)
    const current = props.from + (props.to - props.from) * easeOut(progress)
    display.value = formatNumber(current)
    if (progress < 1) requestAnimationFrame(tick)
  }

  requestAnimationFrame(tick)
})
</script>

<template>
  <span ref="root">{{ display }}</span>
</template>
