// src/components/experience/experience.tsx
import React, { Component } from 'react';
import { ExperienceProps } from '@/types';
import { LanguageContextType } from '../languageProvider';
import ExperienceItem from './experienceItem';
import About from './about';
import styles from './experience.module.css';
import { LanguageContext } from '../languageProvider';
import AnimatedComponent from '../AnimatedComponent';

class Experience extends Component<ExperienceProps> {
  static contextType = LanguageContext;
  context!: React.ContextType<typeof LanguageContext>;

  render() {
    const { experiences, about, contact, interests } = this.props;
    const { t } = this.context as LanguageContextType;

    return (
      <section id="experience" className={`section ${styles.experienceSection}`}>
        <div className="container">
          <AnimatedComponent
            direction="bottom"
            distance={50}
            duration={0.8}
            once={true}
            threshold={0.1}
          >
            <h2 className={'sectionTitle'}>{t('experience.title')}</h2>
          </AnimatedComponent>

          <div className={styles.experienceContent}>
            <div className={styles.experienceTimeline}>
              {experiences.map((experience, index) => (
                <ExperienceItem
                  key={index}
                  experience={experience}
                  index={index}
                />
              ))}
            </div>

            <About
              about={about}
              contact={contact}
              interests={interests}
            />
          </div>
        </div>
      </section>
    );
  }
}

export default Experience;

// src/components/portfolio/Experience.vue
<script setup lang="ts">
import { useLanguage } from "../../composables/useLanguage"
import AnimatedReveal from "./AnimatedReveal.vue"
import ExperienceItem from "./ExperienceItem.vue"
import About from "./About.vue"
import type { Bilingual, Contact, Experience as ExperienceType, Interests } from "../../types/portfolio"

defineProps<{
  experiences: ExperienceType[]
  about:       Bilingual
  contact:     Contact
  interests:   Interests
}>()

const { t } = useLanguage()
</script>

<template>
  <section id="experience" class="experience-section">
    <div class="container">
      <AnimatedReveal direction="bottom" :distance="50" :duration="0.8" :threshold="0.1">
        <h2 class="section-title">{{ t("experienceTitle") }}</h2>
      </AnimatedReveal>

      <div class="experience-section__content">
        <div class="experience-section__timeline">
          <ExperienceItem
            v-for="(experience, idx) in experiences"
            :key="idx"
            :experience="experience"
            :index="idx"
          />
        </div>

        <About :about="about" :contact="contact" :interests="interests" />
      </div>
    </div>
  </section>
</template>

<style scoped>
.experience-section {
  background: linear-gradient(to bottom, var(--color-background), var(--color-background-secondary));
  padding-top: var(--spacing-5xl);
  padding-bottom: var(--spacing-6xl);
}

.experience-section__content {
  margin-top: var(--spacing-3xl);
}

.experience-section__timeline {
  margin-bottom: var(--spacing-3xl);
}

@media (max-width: 768px) {
  .experience-section__content { margin-top: var(--spacing-xl); }
}
</style>
